##==============================================================================
## Alpine
## ------
## https://medium.com/@jeromegamez/build-your-own-php-docker-image-3c55c9e29b59
## https://github.com/kreait/docker-images/blob/master/Makefile
##
## Multi-stage
## -----------
## https://docs.docker.com/develop/develop-images/multistage-build/
##
## A collection of delicious docker recipes
## ----------------------------------------
## https://github.com/vimagick/dockerfiles
##==============================================================================

version: "3.2"
services:
  apache:
    build:
      context: ./apache
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mariadb
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - html:/var/www/html
      #- ./html:/var/www/html
    container_name: "${CONTAINER_APACHE_NAME}"
  php:
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - html:/var/www/html
      #- ./html:/var/www/html
    container_name: "${CONTAINER_PHP_NAME}"
  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    environment:
      MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MARIADB_DATABASE}"
      MYSQL_USER: "${MARIADB_USERNAME}"
      MYSQL_PASSWORD: "${MARIADB_PASSWORD}"
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
      #- ./mariadb:/var/lib/mysql
    restart: always
    container_name: "${CONTAINER_MARIADB_NAME}"
  adminer:
    image: adminer:fastcgi
    networks:
      - backend
    ports:
      - "8080:8080"
    restart: always
    container_name: "${CONTAINER_ADMINER_NAME}"
  ssh:
    #image: github.com/chamunks/alpine-openssh
    #image: vimagick/openssh
    build:
      context: ./ssh
    #environment:
      #- USERNAME=www-data
      #- PASSWORD=www-data
    networks:
      - backend
    ports:
      - "2222:22"
    volumes:
      - html:/var/www/html
      #- ./ssh:/data/.ssh:ro
      ## Uncomment next line if you're bringing your own sshd_config
      # - ./etc/ssh/sshd_config:/etc/ssh/sshd_config:ro
    restart: always
    container_name: "${CONTAINER_SSH_NAME}"
  samba:
    build:
      context: ./samba
    networks:
      - backend
    ports:
      - "445:445"
    volumes:
      - html:/var/www/html
    restart: always
    container_name: "${CONTAINER_SAMBA_NAME}"
networks:
  backend:
  frontend:
volumes:
  html:
  mariadb: