##==============================================================================
## Alpine
## ------
## https://medium.com/@jeromegamez/build-your-own-php-docker-image-3c55c9e29b59
## https://github.com/kreait/docker-images/blob/master/Makefile
##
## Multi-stage
## -----------
## https://docs.docker.com/develop/develop-images/multistage-build/
##
## A collection of delicious docker recipes
## ----------------------------------------
## https://github.com/vimagick/dockerfiles
##==============================================================================

version: "3.2"
services:
  apache:
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    image: vavyskov/apache:alpine
#    build:
#      context: ./apache
#      args:
#        APACHE_VERSION: ${APACHE_VERSION}
    environment:
      VIRTUAL_HOST: ${COMPOSE_PROJECT_NAME}.local
      USER_HOME: ${USER_HOME}
      DOCUMENT_ROOT: ${DOCUMENT_ROOT}
    depends_on:
      - php
      - mariadb
    networks:
      - backend
      - frontend
#    ports:
#      - "8001:80"
#    expose:
#      - "80"
    volumes:
      - html:/var/www/html
      #- ./html:/var/www/html
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    image: vavyskov/php:7.2-fpm-alpine
#    build:
#      context: ./php
#      args:
#        PHP_VERSION: ${PHP_VERSION}
    environment:
      USER_HOME: ${USER_HOME}
      DOCUMENT_ROOT: ${DOCUMENT_ROOT}
    networks:
      - backend
    volumes:
      - html:/var/www/html
      #- ./html:/var/www/html
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    image: mariadb:${MARIADB_VERSION:-latest}
    environment:
      MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MARIADB_DATABASE}"
      MYSQL_USER: "${MARIADB_USERNAME}"
      MYSQL_PASSWORD: "${MARIADB_PASSWORD}"
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
      #- ./mariadb:/var/lib/mysql
    #restart: always
  adminer:
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    image: adminer:fastcgi
    networks:
      - backend
    ports:
      - "8080:8080"
  ssh:
    container_name: ${COMPOSE_PROJECT_NAME}_ssh
    #image: github.com/chamunks/alpine-openssh
    #image: vimagick/openssh
#    image: vavyskov/ssh:vavyskov-php-7.2-fpm-alpine
    build:
      context: ./ssh
    environment:
      USER_NAME: "${USER_NAME}"
      USER_PASSWORD: "${USER_PASSWORD}"
      USER_GROUP: "${USER_GROUP}"
      USER_HOME: "${USER_HOME}"
    networks:
      - backend
    ports:
      - "2222:22"
    volumes:
      - html:/var/www/html
      #- ./ssh:/data/.ssh:ro
      ## Uncomment next line if you're bringing your own sshd_config
      # - ./etc/ssh/sshd_config:/etc/ssh/sshd_config:ro
  samba:
    container_name: ${COMPOSE_PROJECT_NAME}_samba
    image: vavyskov/samba:alpine
#    build:
#      context: ./samba
    environment:
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      USER_GROUP: ${USER_GROUP}
      USER_HOME: ${USER_HOME}
    networks:
      - backend
    ports:
      - "445:445"
    volumes:
      - html:/var/www/html
  nginx-proxy:
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    image: jwilder/nginx-proxy:alpine
    environment:
      DEFAULT_HOST: ${COMPOSE_PROJECT_NAME}.local
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  backend:
  frontend:
volumes:
  html:
  mariadb: